In [1]:
from sklearn import datasets

In [5]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [7]:
x = iris.data
y = iris.target
x.shape , y.shape , type(x),type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [8]:
import numpy as np

In [9]:
np.unique(y)

array([0, 1, 2])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y)
X_train.shape ,X_test.shape ,Y_train.shape ,Y_test.shape 

((112, 4), (38, 4), (112,), (38,))

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
log = LogisticRegression()

In [19]:
log.fit(X_train,Y_train)

c:\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [20]:
log.coef_,log.intercept_

(array([[-0.42461652,  0.87344055, -2.27319506, -0.99501266],
        [ 0.49307932, -0.27429343, -0.10837361, -0.92962214],
        [-0.0684628 , -0.59914712,  2.38156867,  1.9246348 ]]),
 array([  9.17650788,   1.66559377, -10.84210165]))

In [23]:
log.predict_proba(X_train[100:104])

array([[1.19155230e-03, 2.06064766e-01, 7.92743682e-01],
       [1.63993691e-05, 7.60558548e-02, 9.23927746e-01],
       [3.94670629e-03, 7.88079951e-01, 2.07973342e-01],
       [1.51537488e-05, 7.67744197e-02, 9.23210427e-01]])

In [24]:
log.predict(X_train[100:104])

array([2, 2, 1, 2])

In [26]:
0.00119155230+ 0.206064766+0.792743682

1.0000000003

In [27]:
from sklearn import metrics

In [32]:
y_pred = log.predict(X_train)

In [33]:
y_pred

array([2, 0, 2, 2, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 0, 2, 2,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1,
       2, 2, 1, 1, 1, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 1, 2, 2, 0, 0, 2, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 1, 1,
       2, 2, 1, 1, 0, 0, 2, 2, 2, 0, 2, 1, 2, 2, 1, 2, 0, 1, 2, 2, 2, 0,
       2, 2])

In [34]:
Y_train

array([2, 0, 2, 2, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 0, 2, 2,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1,
       2, 2, 2, 1, 1, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 1, 2, 2, 0, 0, 2, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 2, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 1, 1,
       2, 2, 1, 1, 0, 0, 1, 2, 2, 0, 2, 1, 2, 2, 1, 2, 0, 1, 2, 2, 2, 0,
       2, 2])

In [35]:
import pandas as pd

In [38]:
print(metrics.classification_report(Y_train,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.97      0.91      0.94        35
           2       0.92      0.97      0.95        37

    accuracy                           0.96       112
   macro avg       0.96      0.96      0.96       112
weighted avg       0.97      0.96      0.96       112



In [40]:
metrics.confusion_matrix(Y_train,y_pred)

array([[40,  0,  0],
       [ 0, 32,  3],
       [ 0,  1, 36]], dtype=int64)